<?php

function opentools_router_init() {
  if(arg(0) == "opentools") {
    drupal_goto("node/add/wiki", array("query" => array("parent_type" => arg(2))));
  }
}

function opentools_router_menu() {
  $items['opentools/add/%'] = array(
    "page callback" => "opentools_router_route",
    "access callback" => "opentools_access_add",
  );
  return $items;
}

function opentools_access_add() {
  return TRUE;
}

function opentools_router_route() {
  return "";
}

