<?php
/**
 * @file
 * Code for the farmhack feature.
 */

include_once 'farmhack.features.inc';

function farmhack_init() {

}

function farmhack_form_alter(&$form, &$form_state, $form_id) {

}

function farmhack_custom_theme() {
  $path = current_path();
  $alias = drupal_get_path_alias($path);
  $args = explode('/', $alias);
  if ($args[0] == 'library') {
    return 'bootstrap_farmhack';
  }
}

