<?php

function farmhack_rest_api_menu() {
  $items['api/user'] = array(
    'page callback' => 'farmhack_rest_api_user',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/nodes/changed'] = array(
    'page callback' => 'farmhack_rest_api_nodes_by_changed',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/comments/changed'] = array(
    'page callback' => 'farmhack_rest_api_comments_by_changed',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  return $items;
}

function farmhack_rest_api_user() {
  global $user;
  drupal_json_output($user);
}

/*
 * @todo Get some offset and limit parameters going

 Get the 
 type
 user
 title
 body
 image
 related forum

 */
function farmhack_rest_api_nodes_by_changed() {
  $response = array();
  $results = db_query("SELECT nid, changed FROM {node} ORDER BY changed DESC LIMIT 10");
  foreach($results as $result) {
    $response[] = node_load($result->nid);
  }
  drupal_json_output($response);
}

/*
 * @todo Get some offset and limit parameters going
 Get the
 title
 body
 comment on
 related forum
 */
function farmhack_rest_api_comments_by_changed() {
  $response = array();
  $results = db_query("SELECT cid, changed FROM comment ORDER BY changed DESC LIMIT 10");
  foreach($results as $result) {
    $response[] = comment_load($result->cid);
  }
  drupal_json_output($response);
}

