<?php

function farmhack_rest_api_menu() {
  $items['api/user'] = array(
    'page callback' => 'farmhack_rest_api_user',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/blogs/recent'] = array(
    'page callback' => 'farmhack_rest_api_blogs',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/featured-tools'] = array(
    'page callback' => 'farmhack_rest_api_featured_tools',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/nodes/changed'] = array(
    'page callback' => 'farmhack_rest_api_nodes_by_changed',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

  $items['api/comments/changed'] = array(
    'page callback' => 'farmhack_rest_api_comments_by_changed',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  
  $items['api/events'] = array(
    'page callback' => 'farmhack_rest_api_events',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  $items['api/events/upcoming'] = array(
    'page callback' => 'farmhack_rest_api_events_upcoming',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  
  // Redirects
  $items['content/new-problem-statement-wiki'] = array(
    'page callback' => 'new_problem_statement_wiki_redirect',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );
  $items['content/new-event-topic'] = array(
    'page callback' => 'new_event_topic_redirect',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE
  );

;


  return $items;
}

function farmhack_rest_api_user() {
  global $user;
  drupal_json_output($user);
}

function farmhack_rest_api_featured_tools() {
  $response = array();
  $results = db_query('SELECT nid, changed FROM node WHERE type=:type ORDER BY changed DESC LIMIT 1', array('type'=>'tools'));
  foreach($results as $result) {
    $node = node_load($result->nid);
    $user = user_load($node->uid);
    $node->userPhotoFileName = $user->picture->filename;
    $response[] = $node;
  }
  drupal_json_output($response);
}


function farmhack_rest_api_blogs() {
  $response = array();
  $results = db_query('SELECT nid, changed FROM node WHERE type=:type ORDER BY changed DESC LIMIT 1', array('type'=>'blog'));
  foreach($results as $result) {
    $node = node_load($result->nid);
    $user = user_load($node->uid);
    $node->userPhotoFileName = $user->picture->filename;
    $response[] = $node;
  }
  drupal_json_output($response);
}

/*
 * @todo Get some offset and limit parameters going

 Get the 
 type
 user
 title
 body
 image
 related forum

 */
function farmhack_rest_api_nodes_by_changed() {
  $response = array();
  $results = db_query("SELECT nid, changed FROM {node} ORDER BY changed DESC LIMIT 30");
  foreach($results as $result) {
    $node = node_load($result->nid);
    $user = user_load($node->uid);
    $node->userPhotoFileName = $user->picture->filename;
    $response[] = $node;
  }
  drupal_json_output($response);
}

/*
 * @todo Get some offset and limit parameters going
 Get the
 title
 body
 comment on
 related forum
 */
function farmhack_rest_api_comments_by_changed() {
  $response = array();
  $results = db_query("SELECT cid, changed FROM comment ORDER BY changed DESC LIMIT 30");
  foreach($results as $result) {
    $comment = comment_load($result->cid);
    $user = user_load($comment->uid);
    if(is_object($user->picture)) {
      $comment->userPhotoFileName = $user->picture->filename;
    }
    else {
      $comment->userPhotoFileName = "";
    }
    $response[] = $comment;
  }
  drupal_json_output($response);
}

function farmhack_rest_api_events() {
  $response = array();
  drupal_json_output($response);
}


function farmhack_rest_api_events_upcoming() {
  $response = array();
  $results = db_query("SELECT * FROM field_revision_field_dates WHERE entity_type='node' && bundle='event' && field_dates_value2 > UNIX_TIMESTAMP() ORDER BY field_dates_value DESC LIMIT 3");
  foreach($results as $result) {
    $node = node_load($result->entity_id);
    $user = user_load($node->uid);
    $node->userPhotoFileName = $user->picture->filename;
    $response[] = $node;
  }
  drupal_json_output($response);
}

function new_problem_statement_wiki_redirect() {
  header('Location: /node/add/wiki?edit[field_tags][und]=problem%20statement');
}

function new_event_topic_redirect() {
  header('Location: /node/add/forum?edit[field_forum_topic_type][und]=32');
}
